language: node_js
node_js:
- '6.11'
script: npm test
cache:
  directories:
   - node_modules
before_deploy:
 - echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
deploy:
 - provider: script
   skip_cleanup: true
   script: ./scripts/travis-deploy.sh $TRAVIS_BRANCH
   on:
     all_branches: true
     condition: $TRAVIS_BRANCH =~ ^(development|qa|production)$
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
  - secure: Yai/hq8OfSx7uLRHID8BkqnW43D4B2hQyUX0uL/5krAXOKOZJRTVUDuZ2B+hTZi1WrHCvr1gasXwCwihZvJmc2XXQl+MlrQzRjVim9p3MIYJNSEtsQLWQWtvCVntr/vIXC/koacw+55IpdhaEuAXGLZSW9EecUArJEWOgjoQdledt8kLjcJA9biSbs392Mz2vH/jzHSfC5pg54o07xCGknLcYRVVyr9qdjHfsYuoauVxDMPHqXGAM5Y6O8Ii5xe2p9f7nsvERhinL/wyJOY6lSw9jF4DyQ/EeVBduM5WxabX14H9eZPEFeM2fC3AzNqSbLNhNu0IsWlvgBXZaxxezkmbKpRu+Igqjekl/OsHtEA+3Cp3u9PIN7QdaNXAunAiu2YwFKgi365Q+f11vDKHGhKyEwyNv2PGi0ypK954W9WtKjJTIE708o61Xet2L22rA3XhAq1ZYg7Q1aHEbwcmZ4ZJRcDly1r8MkW1md+3Bt1wCNB00yOXoYoLEXlPN0B9qB9XHxA3HoYH3ovLUQS3qrn6DfgSjH1LW7dIQZorH/a5ar/DNtaB+j5a1+fWKXRiHr76691JWEOE5/v1OsTHoIPHn+rNt3NRqOkXUSwDooJH4t2HVHbWjEb+05SUEK8mqv6xcivfgkVuRiTUh8bdlskWkhvScLheCws/7rWz8JQ=
  - secure: DRnipGRl8Qnhi89cfiKoQIQVv0X+XG3imHlLvMdYJBq/FEXsQ3Qu74jmnxkPe6yPuUyeVfjP3OPMRd8HaxVC2gx7cGNDhoiR2YOP2LsQhetrVX+fs5e8O1m4Pq5i8MCZxQapnSVcJ23IjE2vj3pXyRby6xNzMFp3yN+b5ZnDp7FnmLHfqlPPlkZHD460oGDzOhd/AF2mVG10w3PvpikOUga8Wbqwemn5L4g4/mzmFsY36APHdZRpsJNldvMjLENdB+bDor2lz2gKacFOF1aj+Hfub+a0bcYstxM3P5L6yaTbfnBAzJLwI1o0Dtrzybxds8GFUDcQA2tbDYsfAeecG41N6IdPrRNo5Muy5lsGzfjGqy7gDFN9XGbdT+WyQC+Glmk5LrcRzT8KgbWhaiY4yB8ps3FffiM3uSDD1EgFo0pWTJ3zDKQDqWp3OnlG0BGrjuqPw0ikbhqpqSrR+qBPY0OpLSWZ1UopvoHLkz0epMHn9YiUg+JLBR9apwcgJT3Fwu5na4dVK7K0qa49y9MQSAFOyaUYEO2DI6WPQLEKfI1lbo7FIaf2TAfHnrFTv5lBxcxEPcvxYdcDbOdmSwF1S7dI3lb5J+Pwo5fCh+fBp3H6xnOTTaNUl0qxd2+RrGJ3LfViR2pLDyCBHVZTjoxrxI3LgcP/6MfJfpXNiKTGaEQ=
  - secure: XV0TPhGyjevXu6dK0Xau6pLsTLbNrj+YiSn+u/GOunIPCSu21n1IhbXsSYND4x9DVOlc2wtHSO1UvlfSs683yEJpG22KNgT9f6SayxJTVjuY3sftuBhjJ256cra8aFKTemtw0HDRnHwvr0tJCfdMu4vPeFnvkG3OX5b2YXnurl2ETzCuEmWh/zcijer9QiP7ZF7wuE9nR4+/cKTf5xfwiuWn1TUJLnbWaB9omGXm5Dw7nrlx7bVpyJ2pQmnSvrpTotI46TClk5L73drVb82AMkUZ2/aoFHdT+BfE2okKasPepv1ntQ3DcAQuE8E9T+sHmGQWNjDjLAbGQ93n7Jx0nH76eHpQ+vt5nwmDmpqO9Dvimg2WtD5vDi5BJ5nEIy6wwhOJVQ0fhE6oyMpCZWyPREQQOuOJpq0SBMRbq25TcRXsFcfMfEANeM6gbBroI+DfJQ06tImmGJnTKqGIO2HhGQbHpToysIG8CnhQ/b7sZd4tKOGzcwrSO8as02uVl7LMyav9RXTYCqkihtra1b9N6uJo0kCxdC6jLESINHWemF1Mfm3J5V+xK28L6wB/wTjtf73uLPydOKkcLS4uLB86GjCVlFb1J9934XHVR0l++1HOwj9DcSDkD0k5qJKBq2nK3xoWhmkjYeV1U0oMCircWaEIg2KeGzFyHwEWpp2HN7c=
